# Generated by Django 2.2.16 on 2022-10-17 17:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualPrivateServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cpu', models.PositiveSmallIntegerField(verbose_name='количество ядер')),
                ('ram', models.PositiveSmallIntegerField(verbose_name='объем RAM')),
                ('hdd', models.PositiveIntegerField(verbose_name='объем HDD')),
                ('status', models.CharField(choices=[('started', 'Работает'), ('blocked', 'Заблокирован'), ('stopped', 'Остановлен')], default='stopped', max_length=7, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'VPS',
                'default_related_name': 'servers',
            },
        ),
    ]
